[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x"]
aptPkgs = []

[phases.install]
cmds = [
  "npm install --omit=dev --no-audit --no-fund --ignore-engines"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm start"

[staticAssets]
outputDir = "build"